### ISSUE TITLE
slf4j implementation conflict

### ISSUE THREAD

**Issue by hwellmann** [AxonFramework/cdi#18]
`slf4j-simple` should have test scope, not runtime scope.

A Maven artifact to be used as a library should not depend on any slf4j implementation with runtime or compile scope. This is likely to cause conflicts with any slf4j dependencies defined by the user of this library.

**Comment by m-reza-rahman** [comment]
Allard will review this question and provide his opinion. We want to be consistent with whatever Axon Framework proper does in this regard.

**Comment by abuijze** [comment]
I agree. Only the API should have compile scope dependency. The other slf4j dependencies should have test scope.
This is also how it's done in Axon Framework itself.

**Comment by m-reza-rahman** [comment]
Resolved in 3.3-alpha1.
